### ISSUE TITLE
limitation in `wheel_architecture.sh`

### ISSUE THREAD

**Issue by ostueker** [ComputeCanada/wheels_builder#11] opened 2020-07-07 18:30 UTC
I have successfully unmanylinux'ed the Open3D 0.10.0.0 wheel with:
```console
$ unmanylinuxize.sh --package open3d --version 0.10.0.0                                                                            
[...]
'open3d-0.10.0.0-cp36-cp36m-linux_x86_64.whl' -> '../open3d-0.10.0.0-cp36-cp36m-linux_x86_64.whl'
'open3d-0.10.0.0-cp37-cp37m-linux_x86_64.whl' -> '../open3d-0.10.0.0-cp37-cp37m-linux_x86_64.whl'
'open3d-0.10.0.0-cp38-cp38-linux_x86_64.whl' -> '../open3d-0.10.0.0-cp38-cp38-linux_x86_64.whl'
```
and when I have the  `wheel_architecture.sh` guess the architecture, I get:

```console
$ wheel_architecture.sh open3d-0.10.0.0-cp37-cp37m-linux_x86_64.whl 
generic generic
```

Looks reasonable? 

Well, if (for example) I create a virtualenv from `module load StdEnv/2020 python/3.7.7`
and look at the ldd output everything looks just fine:

```console
(env37) $ ldd env37/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007fffbb0d9000)
        libGL.so.1 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/x86_64/libGL.so.1 (0x00002ab037c0b000)
        librt.so.1 => /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/librt.so.1 (0x00002ab037e97000)
        libdl.so.2 => /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libdl.so.2 (0x00002ab037ea1000)
        libX11.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libX11.so.6 (0x00002ab037ea6000)
        libstdc++.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/libstdc++.so.6 (0x00002ab037fea000)
        libm.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libm.so.6 (0x00002ab038262000)
        libgomp.so.1 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/libgomp.so.1 (0x00002ab0383a5000)
        libgcc_s.so.1 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/libgcc_s.so.1 (0x00002ab0383dd000)
        libpthread.so.0 => /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libpthread.so.0 (0x00002ab0383f7000)
        libc.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libc.so.6 (0x00002ab038417000)
        /cvmfs/soft.computecanada.ca/gentoo/2020/lib64/ld-linux-x86-64.so.2 (0x00002ab036e93000)
        libGLX.so.0 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/x86_64/libGLX.so.0 (0x00002ab0385d2000)
        libXext.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libXext.so.6 (0x00002ab038806000)
        libGLdispatch.so.0 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/x86_64/libGLdispatch.so.0 (0x00002ab03881b000)
        libxcb.so.1 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libxcb.so.1 (0x00002ab038ad1000)
        libXau.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libXau.so.6 (0x00002ab038afb000)
        libXdmcp.so.6 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libXdmcp.so.6 (0x00002ab038b00000)
        libbsd.so.0 => /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libbsd.so.0 (0x00002ab038b08000)
```

But if I start from `module load StdEnv/2018.3 python/3.7.4` and do the same, the GLIBC from NIX is clearly too old:

```console
(env374) $ ldd env374/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so 
env374/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so: /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libm.so.6: version `GLIBC_2.27' not found (required by env374/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so)
        linux-vdso.so.1 (0x00007ffd4a599000)
        libGL.so.1 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libGL.so.1 (0x00002adb0fa4a000)
        librt.so.1 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/librt.so.1 (0x00002adb0fcd5000)
        libdl.so.2 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libdl.so.2 (0x00002adb0fedd000)
        libX11.so.6 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libX11.so.6 (0x00002adb100e1000)
        libstdc++.so.6 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libstdc++.so.6 (0x00002adb10421000)
        libm.so.6 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libm.so.6 (0x00002adb107f8000)
        libgomp.so.1 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libgomp.so.1 (0x00002adb10afd000)
        libgcc_s.so.1 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libgcc_s.so.1 (0x00002adb10d33000)
        libpthread.so.0 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libpthread.so.0 (0x00002adb10f49000)
        libc.so.6 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6 (0x00002adb11166000)
        /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib64/ld-linux-x86-64.so.2 (0x00002adb0eb08000)
        libGLX.so.0 => /cvmfs/soft.computecanada.ca/nix/store/sxdgs7s7y6llk1ahzdca5nzwad482s7i-libglvnd-1.0.0/lib/libGLX.so.0 (0x00002adb11504000)
        libXext.so.6 => /cvmfs/soft.computecanada.ca/nix/store/jnwdijqqadn87kj4rv246pmascjlw2mv-libXext-1.3.3/lib/libXext.so.6 (0x00002adb11736000)
        libxcb.so.1 => /cvmfs/soft.computecanada.ca/nix/store/vlningalayif6h9jzdkzczhr1c17q84a-libxcb-1.12/lib/libxcb.so.1 (0x00002adb11948000)
        libXau.so.6 => /cvmfs/soft.computecanada.ca/nix/store/ipbqjzq1ljn2ca7j67mhvfsml46c5b5c-libXau-1.0.8/lib/libXau.so.6 (0x00002adb11b71000)
        libXdmcp.so.6 => /cvmfs/soft.computecanada.ca/nix/store/lfjsq4xyrh7vj14ilrkxccd7nqbnjava-libXdmcp-1.1.2/lib/libXdmcp.so.6 (0x00002adb11d75000)
        libGLdispatch.so.0 => /cvmfs/soft.computecanada.ca/nix/store/sxdgs7s7y6llk1ahzdca5nzwad482s7i-libglvnd-1.0.0/lib/libGLdispatch.so.0 (0x00002adb11f7b000)
```

```console
(env374) $ python -c "import open3d; print(open3d.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/stuekero/wheels/env374/lib/python3.7/site-packages/open3d/__init__.py", line 47, in <module>
    from open3d.open3d_pybind import camera
ImportError: /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libm.so.6: version `GLIBC_2.27' not found (required by /home/stuekero/wheels/env374/lib/python3.7/site-packages/open3d/open3d_pybind.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by ostueker** [comment] 2020-07-07 19:00
Another example for misleading results of `wheel_architecture.sh`:
```console
$ module load StdEnv/2016.4
$ build_wheel.sh --package pyzmq --version 19.0.1
$ wheel_architecture.sh pyzmq-19.0.1-cp37-cp37m-linux_x86_64.whl 
./zmq/backend/cython/constants.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
./zmq/backend/cython/_proxy_steerable.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
./zmq/backend/cython/error.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
./zmq/backend/cython/message.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
./zmq/backend/cython/socket.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
./zmq/backend/cython/_poll.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
./zmq/backend/cython/_version.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
./zmq/backend/cython/utils.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
./zmq/backend/cython/_device.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
./zmq/backend/cython/context.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
./zmq/devices/monitoredqueue.cpython-37m-x86_64-linux-gnu.so is nix generic, rpath=/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/zeromq/4.2.5/lib:
nix generic
```
Okay, NIX it is.

But the same in StdEnv/2020:
```console
$ wheel_architecture.sh pyzmq-19.0.1-cp37-cp37m-linux_x86_64.whl 
generic generic
```

Generic? Let's give it a try (install the wheel built under `StdEnv/2020` into the python/3.7.4 env with activated NIX):

```console
$ source env374/bin/activate

(env374) $ pip install --force-reinstall --no-index gentoo/pyzmq-19.0.1-cp37-cp37m-linux_x86_64.whl 
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Processing ./gentoo/pyzmq-19.0.1-cp37-cp37m-linux_x86_64.whl
Installing collected packages: pyzmq
  Found existing installation: pyzmq 19.0.1
    Uninstalling pyzmq-19.0.1:
      Successfully uninstalled pyzmq-19.0.1
Successfully installed pyzmq-19.0.1

(env374) $ python -c "import zmq; print(zmq.__version__)"                                                                                   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/cython/utils.cpython-37m-x86_64-linux-gnu.so: undefined symbol: zmq_curve_public

(env374) $ ldd /home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/cython/utils.cpython-37m-x86_64-linux-gnu.so
/home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/cython/utils.cpython-37m-x86_64-linux-gnu.so: /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libm.so.6: version `GLIBC_2.29' not found (required by /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.7/lib/libpython3.7m.so.1.0)
/home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/cython/utils.cpython-37m-x86_64-linux-gnu.so: /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6: version `GLIBC_2.25' not found (required by /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.7/lib/libpython3.7m.so.1.0)
/home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/cython/utils.cpython-37m-x86_64-linux-gnu.so: /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6: version `GLIBC_2.26' not found (required by /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.7/lib/libpython3.7m.so.1.0)
/home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/cython/utils.cpython-37m-x86_64-linux-gnu.so: /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6: version `GLIBC_2.28' not found (required by /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.7/lib/libpython3.7m.so.1.0)
        linux-vdso.so.1 (0x00007ffce8ea1000)
        libzmq.so.5 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libzmq.so.5 (0x00002b6585246000)
        librt.so.1 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/librt.so.1 (0x00002b65854ac000)
        libpython3.7m.so.1.0 => /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.7/lib/libpython3.7m.so.1.0 (0x00002b65856b4000)
        libc.so.6 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6 (0x00002b65859f0000)
        libsodium.so.18 => /cvmfs/soft.computecanada.ca/nix/store/xjnc4lm3dxmxlsfcci65x47q083nya4y-libsodium-1.0.10/lib/libsodium.so.18 (0x00002b6585d8e000)
        libpthread.so.0 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libpthread.so.0 (0x00002b6585ff4000)
        libstdc++.so.6 => /cvmfs/soft.computecanada.ca/nix/store/hnr9dpvnz7yi4kx53qc7wpf7r65g8v18-gcc-5.4.0-lib/lib/../lib64/libstdc++.so.6 (0x00002b6586211000)
        libm.so.6 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libm.so.6 (0x00002b6586589000)
        libgcc_s.so.1 => /cvmfs/soft.computecanada.ca/nix/store/hnr9dpvnz7yi4kx53qc7wpf7r65g8v18-gcc-5.4.0-lib/lib/../lib64/libgcc_s.so.1 (0x00002b658688e000)
        libcrypt.so.1 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libcrypt.so.1 (0x00002b6586aa5000)
        libdl.so.2 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libdl.so.2 (0x00002b6586ce0000)
        libutil.so.1 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libutil.so.1 (0x00002b6586ee4000)
        /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib64/ld-linux-x86-64.so.2 (0x00002b6585021000)
```

Conclusion: detection for gentoo in `wheel_architecture.sh` could be improved.

**Comment by mboisson** [comment] 2020-07-07 19:02
Mmm, good point. Although I don't know up front how to improve on it. @bartoldeman, @ccoulombe, any idea ?

**Comment by mboisson** [comment] 2020-07-24 19:34
I've had an idea. We can check the required version of glibc and compare to what we have in gentoo and nix

**Comment by mboisson** [comment] 2020-07-24 19:59
This should be fixed in https://github.com/ComputeCanada/wheels_builder/commit/bbe9f5bb0415d943c4ff88c1e54798dc6a0d3eb4

Can you test ?

**Comment by mboisson** [comment] 2020-07-24 20:11
Actually, I am not able to reproduce your error.

**Comment by mboisson** [comment] 2020-07-24 20:20
Ah, yes I am. But your error is not actually related to the version of GLIBC. `pyzmq` itself does not require a version of GLIBC that is more recent than the one in Nix. 

The actual error is this: 
```
ImportError: /home/stuekero/wheels/env374/lib/python3.7/site-packages/zmq/backend/cython/utils.cpython-37m-x86_64-linux-gnu.so: undefined symbol: zmq_curve_public
``` 

This in turns happens because in Nix, `libzmq.so.5` is installed in the `zmq` module, and the shared object gets a RUNPATH corresponding to that module. On Gentoo, `libzmq.so.5` is installed in the Gentoo prefix. It is therefore not added to the RPATH. If `libzmq.so.5` was in the Nix profile, it would work.

**Comment by mboisson** [comment] 2020-07-24 20:23
Mmmm, actually, `libzmq.so.5` is also available in the Nix profile 🤔

**Comment by mboisson** [comment] 2020-08-24 18:20
Ok, the version in this branch should fix this https://github.com/ComputeCanada/wheels_builder/tree/ldd_in_wheel_architecture

**Comment by mboisson** [comment] 2021-07-29 14:51
This has been merged. Closing this issue. Reopen it if you still encounter the problem.

**Closed by mboisson** 2021-07-29 14:51 UTC
Labels: enhancement
